2025-09-29 16:16:04,969 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-15' coro=<Connection.run.<locals>.init() running at C:\Python313\Lib\site-packages\playwright\_impl\_connection.py:308> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[ProtocolCallback.__init__.<locals>.cb() at C:\Python313\Lib\site-packages\playwright\_impl\_connection.py:228]>
